#!/usr/bin/env bash
# Regenerate assets-data.ts from the 6 PNG files in assets/.
# Run after replacing placeholder PNGs with real ATOLL branding.
#
# Usage:
#   bash supabase/functions/atollcard-wallet-pass/scripts/gen-assets-data.sh

set -euo pipefail

cd "$(dirname "$0")/.."

{
  echo "// Auto-generated by scripts/gen-assets-data.sh"
  echo "// Re-run after editing assets/."
  echo ""
  echo "export const ASSET_BASE64: Record<string, string> = {"
  for f in assets/icon.png "assets/icon@2x.png" "assets/icon@3x.png" assets/logo.png "assets/logo@2x.png" "assets/logo@3x.png"; do
    name=$(basename "$f")
    b64=$(base64 -w0 "$f" 2>/dev/null || base64 "$f" | tr -d '\n')
    echo "  '$name':"
    echo "    '$b64',"
  done
  echo "}"
} > assets-data.ts

echo "Wrote assets-data.ts ($(wc -l < assets-data.ts) lines)"
