-- Phase 2 — PR-Catalogs Seed
-- Source: CD App/Models/pr-catalogs/*.json (DM, IDC, SPEI, EFRI × de/en, version 2024.1)
--
-- Idempotent: nutzt UNIQUE(course_type, language, version) aus 0051.
-- Bei erneutem Apply ON CONFLICT DO UPDATE → Daten werden refresht.

-- Erst alle aktiven Versionen auf inactive setzen (clean reseed)
UPDATE pr_catalogs SET active = false
 WHERE (course_type, language) IN (('DM','de'), ('DM','en'), ('EFRI','de'), ('EFRI','en'), ('IDC','de'), ('IDC','en'), ('SPEI','de'), ('SPEI','en'));

INSERT INTO pr_catalogs (course_type, language, version, data, active)
VALUES ('DM', 'de', '2024.1', $catalog${"course":"DM","version":"2024.1","language":"de","title":"Divemaster","prerequisites":{"minAge":18,"requiredCerts":[{"kind":"Rescue","minMonthsAgo":0},{"kind":"EFR","maxMonthsAgo":24,"note":"Primary & Secondary Care"}],"requiredELearning":null},"slots":[{"code":"WM","order":1,"title":"Wassergewöhnung & Schwimmen","kind":"demoCircuit","scoreSchema":"score1to5","passThreshold":3,"skills":[{"code":"DM.WM.1","title":"400 m Schwimmen","isActive":true},{"code":"DM.WM.2","title":"15 Min. Wassertreten","isActive":true},{"code":"DM.WM.3","title":"800 m Schnorcheln","isActive":true},{"code":"DM.WM.4","title":"100 m Schlepptauchen","isActive":true}]},{"code":"SK24","order":2,"title":"24 Demo-Skills","kind":"demoCircuit","scoreSchema":"score1to5","passThreshold":3,"skills":[{"code":"DM.SK24.1","title":"Ausrüstung montieren","isActive":true},{"code":"DM.SK24.2","title":"Pre-Dive Safety Check","isActive":true},{"code":"DM.SK24.14","title":"CESA","isActive":true},{"code":"DM.SK24.20","title":"Kompassnavigation","isActive":true}]},{"code":"PRAC","order":3,"title":"Praktische Bewertungen","kind":"passFail","scoreSchema":"passFail","skills":[{"code":"DM.PRAC.SAR","title":"Such- und Bergungstauchgang","isActive":true},{"code":"DM.PRAC.DEEP","title":"Tieftauchgang","isActive":true},{"code":"DM.PRAC.SUPER","title":"Skin-Diver-Supervisor","isActive":true}]},{"code":"EXAM","order":4,"title":"Abschlussprüfung","kind":"exam","scoreSchema":"percent","passThreshold":75,"skills":[{"code":"DM.EXAM.FINAL","title":"DM Abschlussprüfung","isActive":true}]},{"code":"MAP","order":5,"title":"Mapping-Projekt","kind":"passFail","scoreSchema":"passFail","skills":[{"code":"DM.MAP.PROJECT","title":"Tauchplatz-Mapping-Projekt","isActive":true}]}]}$catalog$::jsonb, true)
ON CONFLICT (course_type, language, version)
DO UPDATE SET data = EXCLUDED.data, active = EXCLUDED.active;

INSERT INTO pr_catalogs (course_type, language, version, data, active)
VALUES ('DM', 'en', '2024.1', $catalog${"course":"DM","version":"2024.1","language":"en","title":"Divemaster","prerequisites":{"minAge":18,"requiredCerts":[{"kind":"Rescue","minMonthsAgo":0},{"kind":"EFR","maxMonthsAgo":24,"note":"Primary & Secondary Care"}],"requiredELearning":null},"slots":[{"code":"WM","order":1,"title":"Watermanship","kind":"demoCircuit","scoreSchema":"score1to5","passThreshold":3,"skills":[{"code":"DM.WM.1","title":"400m swim","isActive":true},{"code":"DM.WM.2","title":"15min tread water","isActive":true},{"code":"DM.WM.3","title":"800m mask/snorkel","isActive":true},{"code":"DM.WM.4","title":"100m tired diver tow","isActive":true}]},{"code":"SK24","order":2,"title":"24 Skills Demonstration","kind":"demoCircuit","scoreSchema":"score1to5","passThreshold":3,"skills":[{"code":"DM.SK24.1","title":"Equipment assembly","isActive":true},{"code":"DM.SK24.2","title":"Pre-dive safety check","isActive":true},{"code":"DM.SK24.14","title":"CESA","isActive":true},{"code":"DM.SK24.20","title":"Compass navigation","isActive":true}]},{"code":"PRAC","order":3,"title":"Practical Assessments","kind":"passFail","scoreSchema":"passFail","skills":[{"code":"DM.PRAC.SAR","title":"Search & recovery dive","isActive":true},{"code":"DM.PRAC.DEEP","title":"Deep dive","isActive":true},{"code":"DM.PRAC.SUPER","title":"Skin diver supervisor","isActive":true}]},{"code":"EXAM","order":4,"title":"Final Exam","kind":"exam","scoreSchema":"percent","passThreshold":75,"skills":[{"code":"DM.EXAM.FINAL","title":"DM Final Exam","isActive":true}]},{"code":"MAP","order":5,"title":"Mapping Project","kind":"passFail","scoreSchema":"passFail","skills":[{"code":"DM.MAP.PROJECT","title":"Dive site mapping project","isActive":true}]}]}$catalog$::jsonb, true)
ON CONFLICT (course_type, language, version)
DO UPDATE SET data = EXCLUDED.data, active = EXCLUDED.active;

INSERT INTO pr_catalogs (course_type, language, version, data, active)
VALUES ('EFRI', 'de', '2024.1', $catalog${"course":"EFRI","version":"2024.1","language":"de","title":"Emergency First Responder Instructor","prerequisites":{"minAge":18,"requiredCerts":[{"kind":"EFR","maxMonthsAgo":24,"note":"Primary & Secondary Care"}],"requiredELearning":{"kind":"EFRI","minProgressPercent":100,"knowledgeReviewsRequired":true,"examRequired":true}},"slots":[{"code":"KD","order":1,"title":"Knowledge Development","kind":"exam","scoreSchema":"percent","passThreshold":75,"skills":[{"code":"EFRI.KD.EXAM","title":"EFRI Knowledge-Prüfung","isActive":true}]},{"code":"SKILLS","order":2,"title":"Skill-Demonstrationen","kind":"demoCircuit","scoreSchema":"score1to5","passThreshold":3,"skills":[{"code":"EFRI.SKILLS.CPR_ADULT","title":"HLW (Erwachsene)","isActive":true},{"code":"EFRI.SKILLS.CPR_CHILD","title":"HLW (Kind)","isActive":true},{"code":"EFRI.SKILLS.AED","title":"AED-Anwendung","isActive":true},{"code":"EFRI.SKILLS.BLEEDING","title":"Schwere Blutung versorgen","isActive":true},{"code":"EFRI.SKILLS.SHOCK","title":"Schock-Management","isActive":true},{"code":"EFRI.SKILLS.SPINAL","title":"Wirbelsäulenverletzung versorgen","isActive":true},{"code":"EFRI.SKILLS.BANDAGING","title":"Verbände anlegen","isActive":true}]},{"code":"TEACH","order":3,"title":"Lehrpräsentationen","kind":"presentation","scoreSchema":"rubric","minRequired":2,"skills":[{"code":"EFRI.TEACH.KD","title":"Knowledge-Development-Präsentation","isActive":true,"repeatable":true},{"code":"EFRI.TEACH.SKILL","title":"Skill-Practice-Präsentation","isActive":true,"repeatable":true}]},{"code":"FINAL","order":4,"title":"Abschluss-Prüfung","kind":"exam","scoreSchema":"percent","passThreshold":75,"skills":[{"code":"EFRI.FINAL.WRITTEN","title":"Abschluss-Klausur","isActive":true},{"code":"EFRI.FINAL.PRACTICAL","title":"Praktische Fertigkeits-Prüfung","isActive":true}]}]}$catalog$::jsonb, true)
ON CONFLICT (course_type, language, version)
DO UPDATE SET data = EXCLUDED.data, active = EXCLUDED.active;

INSERT INTO pr_catalogs (course_type, language, version, data, active)
VALUES ('EFRI', 'en', '2024.1', $catalog${"course":"EFRI","version":"2024.1","language":"en","title":"Emergency First Responder Instructor","prerequisites":{"minAge":18,"requiredCerts":[{"kind":"EFR","maxMonthsAgo":24,"note":"Primary & Secondary Care"}],"requiredELearning":{"kind":"EFRI","minProgressPercent":100,"knowledgeReviewsRequired":true,"examRequired":true}},"slots":[{"code":"KD","order":1,"title":"Knowledge Development","kind":"exam","scoreSchema":"percent","passThreshold":75,"skills":[{"code":"EFRI.KD.EXAM","title":"EFRI Knowledge Exam","isActive":true}]},{"code":"SKILLS","order":2,"title":"Skill Demonstrations","kind":"demoCircuit","scoreSchema":"score1to5","passThreshold":3,"skills":[{"code":"EFRI.SKILLS.CPR_ADULT","title":"CPR (Adult)","isActive":true},{"code":"EFRI.SKILLS.CPR_CHILD","title":"CPR (Child)","isActive":true},{"code":"EFRI.SKILLS.AED","title":"AED Use","isActive":true},{"code":"EFRI.SKILLS.BLEEDING","title":"Serious Bleeding Management","isActive":true},{"code":"EFRI.SKILLS.SHOCK","title":"Shock Management","isActive":true},{"code":"EFRI.SKILLS.SPINAL","title":"Spinal Injury Management","isActive":true},{"code":"EFRI.SKILLS.BANDAGING","title":"Bandaging","isActive":true}]},{"code":"TEACH","order":3,"title":"Teaching Presentations","kind":"presentation","scoreSchema":"rubric","minRequired":2,"skills":[{"code":"EFRI.TEACH.KD","title":"Knowledge Development Presentation","isActive":true,"repeatable":true},{"code":"EFRI.TEACH.SKILL","title":"Skill Practice Presentation","isActive":true,"repeatable":true}]},{"code":"FINAL","order":4,"title":"Final Assessment","kind":"exam","scoreSchema":"percent","passThreshold":75,"skills":[{"code":"EFRI.FINAL.WRITTEN","title":"Final Written Exam","isActive":true},{"code":"EFRI.FINAL.PRACTICAL","title":"Practical Skill Assessment","isActive":true}]}]}$catalog$::jsonb, true)
ON CONFLICT (course_type, language, version)
DO UPDATE SET data = EXCLUDED.data, active = EXCLUDED.active;

INSERT INTO pr_catalogs (course_type, language, version, data, active)
VALUES ('IDC', 'de', '2024.1', $catalog${"course":"IDC","version":"2024.1","language":"de","title":"Instructor Development Course","prerequisites":{"minAge":18,"requiredCerts":[{"kind":"DM","minMonthsAgo":6},{"kind":"EFR","maxMonthsAgo":24,"note":"Primary & Secondary Care"}],"requiredELearning":{"kind":"IDC","minProgressPercent":100,"knowledgeReviewsRequired":true,"examRequired":true}},"slots":[{"code":"SYS","order":1,"title":"Systems-Prüfungen","kind":"exam","scoreSchema":"percent","passThreshold":75,"skills":[{"code":"IDC.SYS.1","title":"Physik","isActive":true},{"code":"IDC.SYS.2","title":"Physiologie","isActive":true},{"code":"IDC.SYS.3","title":"Ausrüstung","isActive":true},{"code":"IDC.SYS.4","title":"Skills & Umgebung","isActive":true},{"code":"IDC.SYS.5","title":"RDP","isActive":true}]},{"code":"STD","order":2,"title":"Standards-Prüfung","kind":"exam","scoreSchema":"percent","passThreshold":75,"skills":[{"code":"IDC.STD.1","title":"PADI Standards-Prüfung","isActive":true}]},{"code":"SC","order":3,"title":"Skill Circuit","kind":"demoCircuit","scoreSchema":"score1to5","passThreshold":3,"skills":[{"code":"IDC.SC.1","title":"Ausrüstung montieren","isActive":true},{"code":"IDC.SC.2","title":"Pre-Dive Safety Check","isActive":true},{"code":"IDC.SC.14","title":"CESA","isActive":true},{"code":"IDC.SC.15","title":"Schweben","isActive":true},{"code":"IDC.SC.16","title":"Maske ab- und aufsetzen","isActive":true}]},{"code":"KD","order":4,"title":"Knowledge-Development-Präsentationen","kind":"presentation","scoreSchema":"rubric","minRequired":1,"skills":[{"code":"IDC.KD.PRESENTATION","title":"KD-Lehrpräsentation","isActive":true,"repeatable":true}]},{"code":"CW","order":5,"title":"Pool-Teaching-Präsentationen","kind":"presentation","scoreSchema":"rubric","minRequired":1,"skills":[{"code":"IDC.CW.PRESENTATION","title":"Pool-Lehrpräsentation","isActive":true,"repeatable":true}]},{"code":"OW","order":6,"title":"Freiwasser-Teaching-Präsentationen","kind":"presentation","scoreSchema":"rubric","minRequired":2,"skills":[{"code":"IDC.OW.PRESENTATION","title":"Freiwasser-Lehrpräsentation","isActive":true,"repeatable":true}]},{"code":"RES","order":7,"title":"Rescue-Bewertung (Übung 7)","kind":"demoCircuit","scoreSchema":"score1to5","passThreshold":3,"skills":[{"code":"IDC.RES.EX7","title":"Rescue-Übung 7","isActive":true}]},{"code":"WS","order":8,"title":"Workshops","kind":"workshop","scoreSchema":"passFail","skills":[{"code":"IDC.WS.DSD","title":"DSD-Workshop","isActive":true},{"code":"IDC.WS.SF","title":"Skin-Diver- / Refresher-Workshop","isActive":true},{"code":"IDC.WS.PERF","title":"Tarierungs-Workshop","isActive":true}]}]}$catalog$::jsonb, true)
ON CONFLICT (course_type, language, version)
DO UPDATE SET data = EXCLUDED.data, active = EXCLUDED.active;

INSERT INTO pr_catalogs (course_type, language, version, data, active)
VALUES ('IDC', 'en', '2024.1', $catalog${"course":"IDC","version":"2024.1","language":"en","title":"Instructor Development Course","prerequisites":{"minAge":18,"requiredCerts":[{"kind":"DM","minMonthsAgo":6},{"kind":"EFR","maxMonthsAgo":24,"note":"Primary & Secondary Care"}],"requiredELearning":{"kind":"IDC","minProgressPercent":100,"knowledgeReviewsRequired":true,"examRequired":true}},"slots":[{"code":"SYS","order":1,"title":"Systems Exams","kind":"exam","scoreSchema":"percent","passThreshold":75,"skills":[{"code":"IDC.SYS.1","title":"Physics Exam","isActive":true},{"code":"IDC.SYS.2","title":"Physiology Exam","isActive":true},{"code":"IDC.SYS.3","title":"Equipment Exam","isActive":true},{"code":"IDC.SYS.4","title":"Skills & Env Exam","isActive":true},{"code":"IDC.SYS.5","title":"RDP Exam","isActive":true}]},{"code":"STD","order":2,"title":"Standards Exam","kind":"exam","scoreSchema":"percent","passThreshold":75,"skills":[{"code":"IDC.STD.1","title":"PADI Standards Exam","isActive":true}]},{"code":"SC","order":3,"title":"Skill Circuit","kind":"demoCircuit","scoreSchema":"score1to5","passThreshold":3,"skills":[{"code":"IDC.SC.1","title":"Equipment assembly","isActive":true},{"code":"IDC.SC.2","title":"Pre-dive safety check","isActive":true},{"code":"IDC.SC.14","title":"CESA","isActive":true},{"code":"IDC.SC.15","title":"Hover","isActive":true},{"code":"IDC.SC.16","title":"Mask removal & replace","isActive":true}]},{"code":"KD","order":4,"title":"Knowledge Development Presentations","kind":"presentation","scoreSchema":"rubric","minRequired":1,"skills":[{"code":"IDC.KD.PRESENTATION","title":"KD Teaching Presentation","isActive":true,"repeatable":true}]},{"code":"CW","order":5,"title":"Confined Water Teaching Presentations","kind":"presentation","scoreSchema":"rubric","minRequired":1,"skills":[{"code":"IDC.CW.PRESENTATION","title":"CW Teaching Presentation","isActive":true,"repeatable":true}]},{"code":"OW","order":6,"title":"Open Water Teaching Presentations","kind":"presentation","scoreSchema":"rubric","minRequired":2,"skills":[{"code":"IDC.OW.PRESENTATION","title":"OW Teaching Presentation","isActive":true,"repeatable":true}]},{"code":"RES","order":7,"title":"Rescue Assessment (Ex 7)","kind":"demoCircuit","scoreSchema":"score1to5","passThreshold":3,"skills":[{"code":"IDC.RES.EX7","title":"Rescue Exercise 7","isActive":true}]},{"code":"WS","order":8,"title":"Workshops","kind":"workshop","scoreSchema":"passFail","skills":[{"code":"IDC.WS.DSD","title":"Discover Scuba Diving Workshop","isActive":true},{"code":"IDC.WS.SF","title":"Skin Diver / Refresher Workshop","isActive":true},{"code":"IDC.WS.PERF","title":"Peak Performance Buoyancy","isActive":true}]}]}$catalog$::jsonb, true)
ON CONFLICT (course_type, language, version)
DO UPDATE SET data = EXCLUDED.data, active = EXCLUDED.active;

INSERT INTO pr_catalogs (course_type, language, version, data, active)
VALUES ('SPEI', 'de', '2024.1', $catalog${"course":"SPEI","version":"2024.1","language":"de","title":"Specialty Instructor","prerequisites":{"minAge":18,"requiredCerts":[{"kind":"OWSI","minMonthsAgo":0}],"requiredELearning":null},"slots":[{"code":"KD","order":1,"title":"Knowledge Development","kind":"presentation","scoreSchema":"rubric","minRequired":1,"skills":[{"code":"SPEI.KD","title":"Knowledge-Development-Präsentation","isActive":true,"repeatable":true}]},{"code":"DIVES","order":2,"title":"Specialty-Tauchgänge","kind":"demoCircuit","scoreSchema":"passFail","skills":[{"code":"SPEI.DIVE","title":"Specialty-Trainings-Tauchgang","isActive":true,"repeatable":true}]},{"code":"PRES","order":3,"title":"Specialty-Präsentationen","kind":"presentation","scoreSchema":"rubric","minRequired":1,"skills":[{"code":"SPEI.PRES","title":"Specialty-Präsentation im Wasser","isActive":true,"repeatable":true}]}]}$catalog$::jsonb, true)
ON CONFLICT (course_type, language, version)
DO UPDATE SET data = EXCLUDED.data, active = EXCLUDED.active;

INSERT INTO pr_catalogs (course_type, language, version, data, active)
VALUES ('SPEI', 'en', '2024.1', $catalog${"course":"SPEI","version":"2024.1","language":"en","title":"Specialty Instructor","prerequisites":{"minAge":18,"requiredCerts":[{"kind":"OWSI","minMonthsAgo":0}],"requiredELearning":null},"slots":[{"code":"KD","order":1,"title":"Knowledge Development","kind":"presentation","scoreSchema":"rubric","minRequired":1,"skills":[{"code":"SPEI.KD","title":"Knowledge Development Presentation","isActive":true,"repeatable":true}]},{"code":"DIVES","order":2,"title":"Specialty Dives","kind":"demoCircuit","scoreSchema":"passFail","skills":[{"code":"SPEI.DIVE","title":"Specialty Training Dive","isActive":true,"repeatable":true}]},{"code":"PRES","order":3,"title":"Specialty Presentations","kind":"presentation","scoreSchema":"rubric","minRequired":1,"skills":[{"code":"SPEI.PRES","title":"In-Water Specialty Presentation","isActive":true,"repeatable":true}]}]}$catalog$::jsonb, true)
ON CONFLICT (course_type, language, version)
DO UPDATE SET data = EXCLUDED.data, active = EXCLUDED.active;

-- Ein aktiver Katalog pro (course_type, language) → Index aus 0051 enforced das
-- Sanity:
--   SELECT course_type, language, version, jsonb_array_length(data->'slots') AS slots
--     FROM pr_catalogs WHERE active ORDER BY course_type, language;
