-- 0086: Retarget consumer FK constraints from legacy tables → contacts(id)
--
-- PREREQUISITES: Run this query in Supabase Studio first to confirm existing
-- FK names and ON DELETE behaviour before applying this migration:
--
-- SELECT
--   conname                                AS constraint_name,
--   conrelid::regclass                     AS table_name,
--   a.attname                              AS column_name,
--   confrelid::regclass                    AS references_table,
--   CASE confdeltype
--     WHEN 'a' THEN 'NO ACTION'
--     WHEN 'r' THEN 'RESTRICT'
--     WHEN 'c' THEN 'CASCADE'
--     WHEN 'n' THEN 'SET NULL'
--     WHEN 'd' THEN 'SET DEFAULT'
--   END                                    AS on_delete
-- FROM pg_constraint c
-- JOIN pg_attribute  a ON a.attrelid = c.conrelid AND a.attnum = ANY(c.conkey)
-- WHERE c.contype = 'f'
--   AND confrelid::regclass::text IN ('instructors', 'people', 'organizations')
-- ORDER BY conrelid::regclass::text, a.attname;
--
-- Expected FK names (auto-generated by Postgres from inline REFERENCES in CREATE TABLE /
-- ALTER TABLE ADD COLUMN; may differ if Postgres named them differently — the query above
-- shows actuals):
--
--   course_assignments_instructor_id_fkey         → instructors   ON DELETE RESTRICT
--   account_movements_instructor_id_fkey          → instructors   ON DELETE RESTRICT
--   account_movements_created_by_fkey             → instructors   ON DELETE NO ACTION
--   instructor_skills_instructor_id_fkey          → instructors   ON DELETE CASCADE
--   availability_instructor_id_fkey               → instructors   ON DELETE CASCADE
--   communication_entries_created_by_fkey         → instructors   ON DELETE SET NULL
--   device_tokens_instructor_id_fkey              → instructors   ON DELETE CASCADE
--   intake_checklists_checked_by_id_fkey          → instructors   ON DELETE SET NULL
--   performance_records_assessed_by_id_fkey       → instructors   ON DELETE SET NULL
--   course_participants_certified_by_instructor_id_fkey → instructors ON DELETE SET NULL
--   import_logs_triggered_by_fkey                 → instructors   ON DELETE NO ACTION
--   courses_created_by_fkey                       → instructors   ON DELETE NO ACTION
--   course_participants_student_id_fkey           → people        ON DELETE RESTRICT
--   elearning_progress_student_id_fkey            → people        ON DELETE CASCADE
--   intake_checklists_student_id_fkey             → people        ON DELETE CASCADE
--   performance_records_student_id_fkey           → people        ON DELETE CASCADE
--   student_certifications_student_id_fkey        → people        ON DELETE CASCADE
--   communication_entries_contact_id_fkey         → people        ON DELETE CASCADE
--   people_organization_id_fkey                   → organizations ON DELETE SET NULL
--
-- ON DELETE choices:
--   • CASCADE  for pure child-record tables (skills, tokens, elearning, certifications, etc.)
--   • RESTRICT for saldo-bearing tables (account_movements.instructor_id,
--              course_participants.student_id) — don't allow deleting a contact
--              while they still have financial/enrollment records
--   • SET NULL for accountability pointers (assessed_by, checked_by, created_by,
--              triggered_by, certified_by) — the record survives; the "who" becomes NULL
--   • NO ACTION → kept as NO ACTION (same effect as RESTRICT in most cases;
--              preserving original semantic)
--
-- This migration is reversible: to roll back, DROP the new constraints and re-add
-- pointing at the legacy tables with the same ON DELETE behaviour.

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. course_assignments.instructor_id  (instructors → contacts, RESTRICT)
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.course_assignments
  DROP CONSTRAINT IF EXISTS course_assignments_instructor_id_fkey;
ALTER TABLE public.course_assignments
  ADD CONSTRAINT course_assignments_instructor_id_fkey
  FOREIGN KEY (instructor_id) REFERENCES public.contacts(id)
  ON DELETE RESTRICT;

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. account_movements.instructor_id  (instructors → contacts, RESTRICT)
--    Saldo data is precious — never silently delete.
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.account_movements
  DROP CONSTRAINT IF EXISTS account_movements_instructor_id_fkey;
ALTER TABLE public.account_movements
  ADD CONSTRAINT account_movements_instructor_id_fkey
  FOREIGN KEY (instructor_id) REFERENCES public.contacts(id)
  ON DELETE RESTRICT;

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. account_movements.created_by  (instructors → contacts, NO ACTION)
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.account_movements
  DROP CONSTRAINT IF EXISTS account_movements_created_by_fkey;
ALTER TABLE public.account_movements
  ADD CONSTRAINT account_movements_created_by_fkey
  FOREIGN KEY (created_by) REFERENCES public.contacts(id)
  ON DELETE SET NULL;

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. instructor_skills.instructor_id  (instructors → contacts, CASCADE)
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.instructor_skills
  DROP CONSTRAINT IF EXISTS instructor_skills_instructor_id_fkey;
ALTER TABLE public.instructor_skills
  ADD CONSTRAINT instructor_skills_instructor_id_fkey
  FOREIGN KEY (instructor_id) REFERENCES public.contacts(id)
  ON DELETE CASCADE;

-- ─────────────────────────────────────────────────────────────────────────────
-- 5. availability.instructor_id  (instructors → contacts, CASCADE)
--    Note: table is named "availability" (not "availability_blocks")
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.availability
  DROP CONSTRAINT IF EXISTS availability_instructor_id_fkey;
ALTER TABLE public.availability
  ADD CONSTRAINT availability_instructor_id_fkey
  FOREIGN KEY (instructor_id) REFERENCES public.contacts(id)
  ON DELETE CASCADE;

-- ─────────────────────────────────────────────────────────────────────────────
-- 6. communication_entries.created_by  (instructors → contacts, SET NULL)
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.communication_entries
  DROP CONSTRAINT IF EXISTS communication_entries_created_by_fkey;
ALTER TABLE public.communication_entries
  ADD CONSTRAINT communication_entries_created_by_fkey
  FOREIGN KEY (created_by) REFERENCES public.contacts(id)
  ON DELETE SET NULL;

-- ─────────────────────────────────────────────────────────────────────────────
-- 7. device_tokens.instructor_id  (instructors → contacts, CASCADE)
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.device_tokens
  DROP CONSTRAINT IF EXISTS device_tokens_instructor_id_fkey;
ALTER TABLE public.device_tokens
  ADD CONSTRAINT device_tokens_instructor_id_fkey
  FOREIGN KEY (instructor_id) REFERENCES public.contacts(id)
  ON DELETE CASCADE;

-- ─────────────────────────────────────────────────────────────────────────────
-- 8. intake_checklists.checked_by_id  (instructors → contacts, SET NULL)
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.intake_checklists
  DROP CONSTRAINT IF EXISTS intake_checklists_checked_by_id_fkey;
ALTER TABLE public.intake_checklists
  ADD CONSTRAINT intake_checklists_checked_by_id_fkey
  FOREIGN KEY (checked_by_id) REFERENCES public.contacts(id)
  ON DELETE SET NULL;

-- ─────────────────────────────────────────────────────────────────────────────
-- 9. performance_records.assessed_by_id  (instructors → contacts, SET NULL)
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.performance_records
  DROP CONSTRAINT IF EXISTS performance_records_assessed_by_id_fkey;
ALTER TABLE public.performance_records
  ADD CONSTRAINT performance_records_assessed_by_id_fkey
  FOREIGN KEY (assessed_by_id) REFERENCES public.contacts(id)
  ON DELETE SET NULL;

-- ─────────────────────────────────────────────────────────────────────────────
-- 10. course_participants.certified_by_instructor_id  (instructors → contacts, SET NULL)
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.course_participants
  DROP CONSTRAINT IF EXISTS course_participants_certified_by_instructor_id_fkey;
ALTER TABLE public.course_participants
  ADD CONSTRAINT course_participants_certified_by_instructor_id_fkey
  FOREIGN KEY (certified_by_instructor_id) REFERENCES public.contacts(id)
  ON DELETE SET NULL;

-- ─────────────────────────────────────────────────────────────────────────────
-- 11. import_logs.triggered_by  (instructors → contacts, SET NULL)
--     Original had no ON DELETE (= NO ACTION). Upgrading to SET NULL so that
--     archiving an instructor contact doesn't block deletion of the contacts row.
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.import_logs
  DROP CONSTRAINT IF EXISTS import_logs_triggered_by_fkey;
ALTER TABLE public.import_logs
  ADD CONSTRAINT import_logs_triggered_by_fkey
  FOREIGN KEY (triggered_by) REFERENCES public.contacts(id)
  ON DELETE SET NULL;

-- ─────────────────────────────────────────────────────────────────────────────
-- 12. courses.created_by  (instructors → contacts, SET NULL)
--     Original had no ON DELETE (= NO ACTION). Upgrading to SET NULL.
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.courses
  DROP CONSTRAINT IF EXISTS courses_created_by_fkey;
ALTER TABLE public.courses
  ADD CONSTRAINT courses_created_by_fkey
  FOREIGN KEY (created_by) REFERENCES public.contacts(id)
  ON DELETE SET NULL;

-- ─────────────────────────────────────────────────────────────────────────────
-- 13. course_participants.student_id  (people → contacts, RESTRICT)
--     Keeping RESTRICT: a person with enrollments cannot be deleted.
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.course_participants
  DROP CONSTRAINT IF EXISTS course_participants_student_id_fkey;
ALTER TABLE public.course_participants
  ADD CONSTRAINT course_participants_student_id_fkey
  FOREIGN KEY (student_id) REFERENCES public.contacts(id)
  ON DELETE RESTRICT;

-- ─────────────────────────────────────────────────────────────────────────────
-- 14. elearning_progress.student_id  (people → contacts, CASCADE)
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.elearning_progress
  DROP CONSTRAINT IF EXISTS elearning_progress_student_id_fkey;
ALTER TABLE public.elearning_progress
  ADD CONSTRAINT elearning_progress_student_id_fkey
  FOREIGN KEY (student_id) REFERENCES public.contacts(id)
  ON DELETE CASCADE;

-- ─────────────────────────────────────────────────────────────────────────────
-- 15. intake_checklists.student_id  (people → contacts, CASCADE)
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.intake_checklists
  DROP CONSTRAINT IF EXISTS intake_checklists_student_id_fkey;
ALTER TABLE public.intake_checklists
  ADD CONSTRAINT intake_checklists_student_id_fkey
  FOREIGN KEY (student_id) REFERENCES public.contacts(id)
  ON DELETE CASCADE;

-- ─────────────────────────────────────────────────────────────────────────────
-- 16. performance_records.student_id  (people → contacts, CASCADE)
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.performance_records
  DROP CONSTRAINT IF EXISTS performance_records_student_id_fkey;
ALTER TABLE public.performance_records
  ADD CONSTRAINT performance_records_student_id_fkey
  FOREIGN KEY (student_id) REFERENCES public.contacts(id)
  ON DELETE CASCADE;

-- ─────────────────────────────────────────────────────────────────────────────
-- 17. student_certifications.student_id  (people → contacts, CASCADE)
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.student_certifications
  DROP CONSTRAINT IF EXISTS student_certifications_student_id_fkey;
ALTER TABLE public.student_certifications
  ADD CONSTRAINT student_certifications_student_id_fkey
  FOREIGN KEY (student_id) REFERENCES public.contacts(id)
  ON DELETE CASCADE;

-- ─────────────────────────────────────────────────────────────────────────────
-- 18. communication_entries.contact_id  (people → contacts, CASCADE)
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.communication_entries
  DROP CONSTRAINT IF EXISTS communication_entries_contact_id_fkey;
ALTER TABLE public.communication_entries
  ADD CONSTRAINT communication_entries_contact_id_fkey
  FOREIGN KEY (contact_id) REFERENCES public.contacts(id)
  ON DELETE CASCADE;

-- ─────────────────────────────────────────────────────────────────────────────
-- 19. people.organization_id  (organizations → contacts, SET NULL)
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.people
  DROP CONSTRAINT IF EXISTS people_organization_id_fkey;
ALTER TABLE public.people
  ADD CONSTRAINT people_organization_id_fkey
  FOREIGN KEY (organization_id) REFERENCES public.contacts(id)
  ON DELETE SET NULL;
